name: whatsapp_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.2.0
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dashed_circle: ^0.0.2
  emoji_picker_flutter: ^1.5.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.0
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  font_awesome_flutter: ^10.3.0
  get_it: ^7.2.0
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  shared_preferences: ^2.0.15
  story_view: ^0.14.0
  intl: ^0.18.0
  internet_connection_checker_plus: ^1.0.1

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#131A22"
  image: assets/icons/splash.png
  branding: assets/icons/from-meta.png
  branding_mode: bottom
  android: true
  ios: true
  web: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

#flutter pub run flutter_native_splash:create
#flutter pub run flutter_launcher_icons:main

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

